env {
  job.mode = "BATCH"
  parallelism = 1
}

source {
  FakeSource {
    plugin_output = "fake_data"
    row.num = 5
    schema = {
      fields {
        id = int
        name = string
        user_id = string
      }
    }
    rows = [
      {kind=INSERT, id=1, name="Alice", user_id="1001"}
      {kind=INSERT, id=2, name="Bob", user_id="1002"}
      {kind=INSERT, id=3, name="Charlie", user_id="1003"}
      {kind=INSERT, id=4, name="David", user_id="1004"}
      {kind=INSERT, id=5, name="Eve", user_id="1005"}
    ]
  }
}


sink {
  Console {
    source_table_name = "lookup_result"
  }
}
